# Generated by Django 3.2.3 on 2021-05-28 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('category', models.CharField(choices=[('Operator', 'Operator'), ('Administrator', 'Administrator'), ('Client', 'Client')], max_length=200, null=True)),
                ('date_created', models.DateTimeField()),
                ('date_expired', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.TextField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('register_code', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
