# Generated by Django 3.2.3 on 2021-05-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcode',
            name='category',
            field=models.CharField(choices=[('worker', 'worker'), ('administrator', 'administrator'), ('client', 'client')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='authcode',
            name='code',
            field=models.CharField(max_length=12),
        ),
    ]
